# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - ignore-for-release
      - release-pr
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Deprecations ⚠️
      labels:
        - deprecation
    - title: Enhancements 🎉
      labels:
        - enhancement
    - title: Templates ⛩️
      labels:
        - template
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documents 🗒️
      labels:
        - document
    - title: Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies

