name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Install dependencies
      run: bun install

    - uses: reviewdog/action-setup@v1.4.0
    - name: Run lint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bun run lint --format=checkstyle |
          reviewdog -f=checkstyle -name=oxlint -reporter=github-pr-review -fail-level=any -filter-mode=nofilter

    - name: Run format check
      run: bun run format:check

    - name: Run typecheck
      run: bun run typecheck

    - name: Build
      run: bun run build

    - name: Run tests
      run: bun test
